package common

import "errors"

var (
	ErrInvalidPacket                      = errors.New("invalid packet")
	ErrInvalidChecksum                    = errors.New("invalid checksum")
	ErrInvalidLength                      = errors.New("invalid length")
	ErrWrittenLengthDoesNotMatch          = errors.New("written length does not match")
	ErrUnknownFunctionCode                = errors.New("unknown function code")
	ErrShortWrite                         = errors.New("short write")
	ErrTimeout                            = errors.New("timeout")
	ErrIgnorePacket                       = errors.New("ignore packet")
	ErrNotOurAddress                      = errors.New("not our address")
	ErrUnsupportedFunctionCode            = errors.New("unsupported function code")
	ErrInvalidFunctionCode                = errors.New("invalid function code")
	ErrInvalidData                        = errors.New("invalid data")
	ErrInvalidAddress                     = errors.New("invalid address")
	ErrInvalidCount                       = errors.New("invalid count")
	ErrInvalidValue                       = errors.New("invalid value")
	ErrResponseValueMismatch              = errors.New("response value mismatch")
	ErrResponseOffsetMismatch             = errors.New("response offset mismatch")
	ErrNotImplemented                     = errors.New("not implemented")
	ErrIllegalFunction                    = errors.New("illegal function")
	ErrIllegalDataAddress                 = errors.New("illegal data address")
	ErrIllegalDataValue                   = errors.New("illegal data value")
	ErrServerDeviceFailure                = errors.New("server failure")
	ErrAcknowledge                        = errors.New("acknowledge")
	ErrServerDeviceBusy                   = errors.New("server busy")
	ErrMemoryParityError                  = errors.New("memory parity error")
	ErrGatewayPathUnavailable             = errors.New("gateway path unavailable")
	ErrGatewayTargetDeviceFailedToRespond = errors.New("gateway target device failed")
	ErrUnknownException                   = errors.New("unknown exception")
	ErrURIIsNil                           = errors.New("uri is nil")
	ErrInvalidScheme                      = errors.New("unsupported scheme")
	ErrMissingValue                       = errors.New("missing value")
	ErrTransportClosing                   = errors.New("transport is closing")
	ErrTransportRequired                  = errors.New("transport is required")
	ErrHandlerRequired                    = errors.New("handler is required")
	ErrInvalidHeader                      = errors.New("invalid header")
	ErrInvalidBaudRate                    = errors.New("invalid baud rate")
	ErrInvalidDataBits                    = errors.New("invalid data bits")
	ErrInvalidParity                      = errors.New("invalid parity")
	ErrInvalidStopBits                    = errors.New("invalid stop bits")
)
